// <auto-generated />
using Book_Management.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_Management.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book_Management.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "F. Scott Fitzgerald",
                            Category = "Fiction",
                            Price = 10.99,
                            PublishedYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Harper Lee",
                            Category = "Fiction",
                            Price = 12.99,
                            PublishedYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "George Orwell",
                            Category = "Dystopian",
                            Price = 9.9900000000000002,
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Stephen Hawking",
                            Category = "Science",
                            Price = 15.49,
                            PublishedYear = 1988,
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Yuval Noah Harari",
                            Category = "History",
                            Price = 18.0,
                            PublishedYear = 2011,
                            Title = "Sapiens"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "J.R.R. Tolkien",
                            Category = "Fantasy",
                            Price = 14.949999999999999,
                            PublishedYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Daniel Kahneman",
                            Category = "Psychology",
                            Price = 16.989999999999998,
                            PublishedYear = 2011,
                            Title = "Thinking, Fast and Slow"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Robert C. Martin",
                            Category = "Computers",
                            Price = 39.990000000000002,
                            PublishedYear = 2008,
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Paulo Coelho",
                            Category = "Fiction",
                            Price = 11.5,
                            PublishedYear = 1988,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            BookId = 10,
                            Author = "Tara Westover",
                            Category = "Biography",
                            Price = 13.199999999999999,
                            PublishedYear = 2018,
                            Title = "Educated"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
